export const sampleProducts = [
  {
    id: "11111111-1111-4111-8111-111111111111",
    name: "Ivory Embroidered Straight Suit Set",
    slug: "ivory-embroidered-straight-suit-set",
    gender: "Women",
    category: "Suits",
    description: "An elegant ivory straight suit set with delicate embroidery and a matching dupatta for festive, casual, and graceful everyday styling.",
    price: 2699,
    compare_at_price: 4499,
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Ivory", "Blush", "Sage"],
    images: ["/suits/ivory-straight-suit.jpg"],
    stock: 15,
    status: "published"
  },
  {
    id: "22222222-2222-4222-8222-222222222222",
    name: "Sage Green Embroidered Lawn Suit",
    slug: "sage-green-embroidered-lawn-suit",
    gender: "Women",
    category: "Suits",
    description: "A soft sage green embroidered lawn suit with dupatta, made for light comfort, elegant detailing, and everyday festive styling.",
    price: 2499,
    compare_at_price: 3999,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Sage Green", "Cream", "Pink"],
    images: ["/suits/sage-lawn-suit.jpg"],
    stock: 12,
    status: "published"
  },
  {
    id: "33333333-3333-4333-8333-333333333333",
    name: "Maroon Embroidered Palazzo Suit Set",
    slug: "maroon-embroidered-palazzo-suit-set",
    gender: "Women",
    category: "Suits",
    description: "A rich maroon festive palazzo suit set with detailed embroidery and a matching dupatta for weddings, events, and special occasions.",
    price: 2599,
    compare_at_price: 3999,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Maroon", "Wine", "Navy"],
    images: ["/suits/maroon-palazzo-suit.jpg"],
    stock: 8,
    status: "published"
  },
  {
    id: "44444444-4444-4444-8444-444444444444",
    name: "Pastel Pink Embroidered Suit Set",
    slug: "pastel-pink-embroidered-suit-set",
    gender: "Women",
    category: "Suits",
    description: "A pastel pink embroidered suit set with matching bottom and dupatta, designed for a soft graceful look and comfortable daily wear.",
    price: 2499,
    compare_at_price: 4499,
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Pastel Pink", "Ivory", "Mint"],
    images: ["/suits/pastel-pink-suit.jpg"],
    stock: 10,
    status: "published"
  },
  {
    id: "55555555-5555-4555-8555-555555555555",
    name: "Lavender Embroidered Suit Set",
    slug: "lavender-embroidered-suit-set",
    gender: "Women",
    category: "Suits",
    description: "A lavender embroidered suit set with a refined finish for semi-formal, festive, and occasion wear.",
    price: 2399,
    compare_at_price: 4299,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Lavender"],
    images: ["/suits/lavender-suit.jpg"],
    stock: 9,
    status: "published"
  },
  {
    id: "66666666-6666-4666-8666-666666666666",
    name: "Black Party Wear Suit Set",
    slug: "black-party-wear-suit-set",
    gender: "Women",
    category: "Suits",
    description: "A black embroidered party wear suit made for festive evenings, celebrations, and elegant occasions.",
    price: 3299,
    compare_at_price: 4999,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Gold"],
    images: ["/suits/black-party-suit.jpg"],
    stock: 6,
    status: "published"
  },
  {
    id: "00000007-0007-4777-8777-000000000007",
    name: "Rose Gold Chikankari Lawn Suit",
    slug: "rose-gold-chikankari-lawn-suit",
    gender: "Women",
    category: "Suits",
    description: "Soft rose gold lawn suit with chikankari-style embroidery and a light dupatta for daily elegance.",
    price: 2199,
    compare_at_price: 3599,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Rose Gold", "Cream"],
    images: ["/suits/pastel-pink-suit.jpg"],
    stock: 18,
    status: "published",
    created_at: "2026-06-07T10:07:00.000Z"
  },
  {
    id: "00000008-0008-4888-8888-000000000008",
    name: "Navy Blue Mirror Work Suit Set",
    slug: "navy-blue-mirror-work-suit-set",
    gender: "Women",
    category: "Suits",
    description: "Navy blue suit with mirror work inspired detailing, perfect for evening gatherings and festive wear.",
    price: 2999,
    compare_at_price: 4799,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Navy Blue", "Silver"],
    images: ["/suits/black-party-suit.jpg"],
    stock: 11,
    status: "published",
    created_at: "2026-06-08T10:08:00.000Z"
  },
  {
    id: "00000009-0009-4999-8999-000000000009",
    name: "Mint Green Printed Lawn Suit",
    slug: "mint-green-printed-lawn-suit",
    gender: "Women",
    category: "Suits",
    description: "Fresh mint green printed lawn suit with a breezy dupatta for summer, casual outings, and comfortable styling.",
    price: 1899,
    compare_at_price: 2999,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Mint Green", "White"],
    images: ["/suits/sage-lawn-suit.jpg"],
    stock: 22,
    status: "published",
    created_at: "2026-06-09T10:09:00.000Z"
  },
  {
    id: "d2b8e5fa-aa76-5eab-b831-f62866ea9788",
    name: "Royal Blue Embroidered Straight Suit",
    slug: "royal-blue-embroidered-straight-suit",
    gender: "Women",
    category: "Suits",
    description: "Royal blue straight suit with neat embroidery and a graceful dupatta for semi-formal and festive occasions.",
    price: 2799,
    compare_at_price: 4499,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Royal Blue"],
    images: ["/suits/lavender-suit.jpg"],
    stock: 14,
    status: "published",
    created_at: "2026-06-10T10:10:00.000Z"
  },
  {
    id: "ca92993a-e2ec-5434-8223-813b2884207b",
    name: "Peach Organza Festive Suit Set",
    slug: "peach-organza-festive-suit-set",
    gender: "Women",
    category: "Suits",
    description: "Peach festive suit set with organza-style dupatta and delicate embroidery for family functions and celebrations.",
    price: 3199,
    compare_at_price: 5199,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Peach", "Gold"],
    images: ["/suits/ivory-straight-suit.jpg"],
    stock: 9,
    status: "published",
    created_at: "2026-06-11T10:11:00.000Z"
  },
  {
    id: "5db30e21-f06b-5097-b1ec-8aa74b47f358",
    name: "Teal Green Palazzo Suit Set",
    slug: "teal-green-palazzo-suit-set",
    gender: "Women",
    category: "Suits",
    description: "Teal green palazzo suit set with a comfortable fit, embroidered accents, and a matching dupatta.",
    price: 2599,
    compare_at_price: 3999,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Teal Green"],
    images: ["/suits/maroon-palazzo-suit.jpg"],
    stock: 13,
    status: "published",
    created_at: "2026-06-12T10:12:00.000Z"
  },
  {
    id: "b5310a0f-da9b-54e4-ab27-e79c5a7f77b8",
    name: "White Cotton Daily Wear Suit",
    slug: "white-cotton-daily-wear-suit",
    gender: "Women",
    category: "Suits",
    description: "Clean white cotton suit set made for simple everyday comfort with a soft dupatta and easy styling.",
    price: 1699,
    compare_at_price: 2599,
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["White", "Ivory"],
    images: ["/suits/ivory-straight-suit.jpg"],
    stock: 25,
    status: "published",
    created_at: "2026-06-13T10:13:00.000Z"
  },
  {
    id: "59b9e1b1-0878-50bd-b54f-1671ed471ee5",
    name: "Mustard Yellow Anarkali Suit",
    slug: "mustard-yellow-anarkali-suit",
    gender: "Women",
    category: "Suits",
    description: "Bright mustard yellow anarkali suit with festive embroidery and a flowy silhouette for a standout ethnic look.",
    price: 2899,
    compare_at_price: 4599,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Mustard Yellow"],
    images: ["/suits/yellow-anarkali.jpg"],
    stock: 10,
    status: "published",
    created_at: "2026-06-13T10:14:00.000Z"
  },
  {
    id: "cd358ca5-fd18-5852-a132-baed0a8d0ca3",
    name: "Wine Red Embroidered Sharara Suit",
    slug: "wine-red-embroidered-sharara-suit",
    gender: "Women",
    category: "Suits",
    description: "Wine red sharara suit with rich embroidery, designed for weddings, parties, and special festive nights.",
    price: 3499,
    compare_at_price: 5999,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Wine Red", "Maroon"],
    images: ["/suits/maroon-palazzo-suit.jpg"],
    stock: 7,
    status: "published",
    created_at: "2026-06-13T10:15:00.000Z"
  },
  {
    id: "7ff27987-5d49-5161-8432-4460acab04f6",
    name: "Sky Blue Printed Suit",
    slug: "sky-blue-printed-suit",
    gender: "Women",
    category: "Suits",
    description: "Sky blue printed suit with a soft look and relaxed fit for day events and comfortable wear.",
    price: 1999,
    compare_at_price: 3199,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Sky Blue", "White"],
    images: ["/suits/lavender-suit.jpg"],
    stock: 19,
    status: "published",
    created_at: "2026-06-13T10:16:00.000Z"
  },
  {
    id: "400d6e92-6f7b-5e99-a68d-aebd5003f1ba",
    name: "Olive Green Embroidered Suit Set",
    slug: "olive-green-embroidered-suit-set",
    gender: "Women",
    category: "Suits",
    description: "Olive green embroidered suit set with classic styling and a matching dupatta for elegant everyday dressing.",
    price: 2399,
    compare_at_price: 3799,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Olive Green"],
    images: ["/suits/sage-lawn-suit.jpg"],
    stock: 16,
    status: "published",
    created_at: "2026-06-13T10:17:00.000Z"
  },
  {
    id: "6371ecbb-2fcb-5d15-8b28-063bf9bbbf69",
    name: "Beige Thread Work Straight Suit",
    slug: "beige-thread-work-straight-suit",
    gender: "Women",
    category: "Suits",
    description: "Beige straight suit with subtle thread work, ideal for office, casual occasions, and graceful modest styling.",
    price: 2299,
    compare_at_price: 3499,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Beige", "Cream"],
    images: ["/suits/ivory-straight-suit.jpg"],
    stock: 20,
    status: "published",
    created_at: "2026-06-13T10:18:00.000Z"
  },
  {
    id: "7ed0e048-5133-5e7d-a4f6-eab6a8e23e85",
    name: "Black Gold Embroidered Suit Set",
    slug: "black-gold-embroidered-suit-set",
    gender: "Women",
    category: "Suits",
    description: "Black suit set with gold embroidery details for party wear, festive evenings, and elegant occasions.",
    price: 3399,
    compare_at_price: 5499,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Gold"],
    images: ["/suits/black-party-suit.jpg"],
    stock: 8,
    status: "published",
    created_at: "2026-06-13T10:19:00.000Z"
  },
  {
    id: "eab6e37c-0ec2-5131-a826-be6f39128898",
    name: "Coral Pink Lawn Suit With Dupatta",
    slug: "coral-pink-lawn-suit-with-dupatta",
    gender: "Women",
    category: "Suits",
    description: "Coral pink lawn suit with soft embroidery and dupatta, made for a fresh feminine everyday look.",
    price: 2099,
    compare_at_price: 3299,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Coral Pink", "Peach"],
    images: ["/suits/pastel-pink-suit.jpg"],
    stock: 17,
    status: "published",
    created_at: "2026-06-13T10:20:00.000Z"
  },
  {
    id: "e3f2c92b-e7a3-54a6-8e21-608bdc1d3842",
    name: "Emerald Green Festive Suit Set",
    slug: "emerald-green-festive-suit-set",
    gender: "Women",
    category: "Suits",
    description: "Emerald green festive suit with detailed accents and a polished finish for parties and family events.",
    price: 3299,
    compare_at_price: 5299,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Emerald Green"],
    images: ["/suits/sage-lawn-suit.jpg"],
    stock: 9,
    status: "published",
    created_at: "2026-06-13T10:21:00.000Z"
  },
  {
    id: "b6140123-1eee-5007-a42c-52fb6ac2b6c0",
    name: "Lilac Embroidered Cotton Suit",
    slug: "lilac-embroidered-cotton-suit",
    gender: "Women",
    category: "Suits",
    description: "Lilac cotton suit with refined embroidery and a comfortable fit for semi-formal and casual wear.",
    price: 2199,
    compare_at_price: 3499,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Lilac", "Lavender"],
    images: ["/suits/lavender-suit.jpg"],
    stock: 15,
    status: "published",
    created_at: "2026-06-13T10:22:00.000Z"
  },
  {
    id: "acbf7794-7df6-5d1e-873f-bcd13b8b5e10",
    name: "Rust Orange Suit Set",
    slug: "rust-orange-suit-set",
    gender: "Women",
    category: "Suits",
    description: "Rust orange suit set with ethnic charm and a flattering fit for festive daytime occasions.",
    price: 2599,
    compare_at_price: 4099,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Rust Orange"],
    images: ["/suits/yellow-anarkali.jpg"],
    stock: 12,
    status: "published",
    created_at: "2026-06-13T10:23:00.000Z"
  },
  {
    id: "ec1f713c-13aa-54e6-841a-8269aee6b01c",
    name: "Cream Zari Work Suit Set",
    slug: "cream-zari-work-suit-set",
    gender: "Women",
    category: "Suits",
    description: "Cream suit set with zari-style detailing and a graceful dupatta for elegant traditional dressing.",
    price: 2999,
    compare_at_price: 4799,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Cream", "Gold"],
    images: ["/suits/ivory-straight-suit.jpg"],
    stock: 10,
    status: "published",
    created_at: "2026-06-13T10:24:00.000Z"
  },
  {
    id: "5260ded4-917e-59d7-a7b9-aae2365b06e9",
    name: "Magenta Party Wear Suit",
    slug: "magenta-party-wear-suit",
    gender: "Women",
    category: "Suits",
    description: "Magenta party wear suit with festive embroidery and a bold color look for celebrations and special events.",
    price: 3199,
    compare_at_price: 4999,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Magenta", "Pink"],
    images: ["/suits/maroon-palazzo-suit.jpg"],
    stock: 8,
    status: "published",
    created_at: "2026-06-13T10:25:00.000Z"
  },
  {
    id: "cd5cb867-b83f-5158-8ed8-4d494b6bffa7",
    name: "Aqua Blue Casual Lawn Suit",
    slug: "aqua-blue-casual-lawn-suit",
    gender: "Women",
    category: "Suits",
    description: "Aqua blue casual lawn suit made for light comfort, easy movement, and simple everyday ethnic style.",
    price: 1799,
    compare_at_price: 2899,
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Aqua Blue"],
    images: ["/suits/sage-lawn-suit.jpg"],
    stock: 24,
    status: "published",
    created_at: "2026-06-13T10:26:00.000Z"
  }
];

export const menCategories = [];
export const womenCategories = ["Suits"];
export const orderStatuses = ["New Order", "Confirmed", "Packed", "Shipped", "Delivered", "Cancelled"];
export const paymentMethods = ["Cash on Delivery", "Manual UPI Payment"];
